#!/usr/bin/env bash
#
# One-shot Ubuntu / Kasm prep for bots-automation (Node 20, system browsers, Playwright).
# Run from any directory, e.g.:  bash setup-kasm-ubuntu.sh
#
# This file contains a GitHub PAT for the test environment. Override with
#   export GITHUB_TOKEN='...'
# before running if needed.
#
set -euo pipefail

GIT_USER_NAME="Boyan Boev"
GIT_USER_EMAIL="boev.boyan85@gmail.com"
GITHUB_USERNAME="${GITHUB_USERNAME:-boyan.boev85-spec}"
# Embedded for local/test VM use only; env GITHUB_TOKEN wins if set.
GITHUB_TOKEN="${GITHUB_TOKEN:-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}"
REPO_SLUG="boevboyan85-spec/udi-payload-collection-automation"
BOTS_DIR_NAME="bots-automation"

git config --global user.email "$GIT_USER_EMAIL"
git config --global user.name "$GIT_USER_NAME"

export GITHUB_USERNAME
export GITHUB_TOKEN

export BOTS_PLATFORM="${BOTS_PLATFORM:-ubuntu}"
export BOTS_IN_CONTAINER="${BOTS_IN_CONTAINER:-1}"
export BOTS_NO_SANDBOX="${BOTS_NO_SANDBOX:-1}"

mkdir -p "$HOME/Documents/git"
cd "$HOME/Documents/git"

REPO_DIR="udi-payload-collection-automation"
if [[ -d "$REPO_DIR/.git" ]]; then
  echo "Repository exists at $PWD/$REPO_DIR — pulling develop..."
  AUTH_URL="https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${REPO_SLUG}.git"
  git -C "$REPO_DIR" pull "$AUTH_URL" develop || git -C "$REPO_DIR" pull "$AUTH_URL"
else
  git clone "https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${REPO_SLUG}.git"
  git -C "$REPO_DIR" remote set-url origin "https://github.com/${REPO_SLUG}.git"
fi

cd "$REPO_DIR/$BOTS_DIR_NAME"

sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg apt-transport-https xz-utils

if ! command -v node >/dev/null 2>&1 || [[ "$(node -p 'process.versions.node.split(".")[0]')" -lt 18 ]]; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi

npm install
npm run install:browsers

GIT_ENV_DIR="${HOME}/.config/bots-automation"
GIT_ENV_FILE="${GIT_ENV_DIR}/git-push.env"
mkdir -p "$GIT_ENV_DIR"
umask 077
{
  echo '# Generated by setup-kasm-ubuntu.sh — chmod 600.'
  printf 'export GITHUB_USERNAME=%q\n' "$GITHUB_USERNAME"
  printf 'export GITHUB_TOKEN=%q\n' "$GITHUB_TOKEN"
} >"${GIT_ENV_FILE}.new"
mv "${GIT_ENV_FILE}.new" "$GIT_ENV_FILE"
chmod 600 "$GIT_ENV_FILE" 2>/dev/null || true
echo "Wrote ${GIT_ENV_FILE} for scripts/push-to-github.sh"

BASHRC_MARK="bots-automation git-push.env"
touch "$HOME/.bashrc"
if ! grep -qF "$BASHRC_MARK" "$HOME/.bashrc" 2>/dev/null; then
  {
    echo ""
    echo "# ${BASHRC_MARK}"
    echo '[[ -f "$HOME/.config/bots-automation/git-push.env" ]] && source "$HOME/.config/bots-automation/git-push.env"'
  } >>"$HOME/.bashrc"
fi

echo "Done. bots-automation directory: $(pwd)"
echo "  cp .env.example .env"
echo "  npm run collect"
